apiVersion: v1
kind: Service
metadata:
  name: alert-telegram-webhook
  namespace: monitoring
  labels:
    app: alert-telegram-webhook
spec:
  type: ClusterIP
  selector:
    app: alert-telegram-webhook
  ports:
    - name: http
      port: 8080
      targetPort: http
