apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: php-nginx-demo
spec:
  type: ClusterIP
  selector:
    app: php-fpm
  ports:
    - name: fpm
      port: 9000
      targetPort: 9000
