apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-log-exporter-config
  namespace: php-nginx-demo
data:
  config.yml: |
    listen:
      port: 4040
      address: "0.0.0.0"

    namespaces:
      - name: nginx
        format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
        source:
          files:
            - /var/log/nginx/access.log
