apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-log-exporter-config
  namespace: php-nginx-demo
data:
  config.yml: |
    listen:
      port: 4040
      address: "0.0.0.0"

    namespaces:
      - name: nginx
        format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time $upstream_response_time"
        histogram_buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
        source:
          files:
            - /var/log/nginx/access.log
